#!/bin/bash

echo "🚀 Arrakis LocalStack - Quick Commands"
echo "====================================="
echo ""
echo "1️⃣  SETUP (run once):"
echo "   ./quick-start.sh"
echo ""
echo "2️⃣  VALIDATE (check everything works):"
echo "   ./validate-setup.sh"
echo ""
echo "3️⃣  TEST ARRAKIS (in terminal 1):"
echo "   make test-basic"
echo ""
echo "4️⃣  SEND MESSAGES (in terminal 2):"
echo "   make send-messages"
echo ""
echo "5️⃣  MONITOR:"
echo "   make status      # Check queue status"
echo "   make logs        # View LocalStack logs"
echo ""
echo "6️⃣  CLEANUP:"
echo "   make purge       # Clear queues"
echo "   make stop        # Stop LocalStack"
echo "   make clean       # Remove everything"
echo ""
echo "💡 Pro tip: Run steps 3 & 4 in separate terminals"
echo "   to see real-time adaptive polling behavior!"
echo ""